Assignment 3/Ass3Solution/eStore/Controllers/HomeController.cs
using DataAccess.Repository;
using eStore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace eStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductRepository _db;
        public HomeController(IProductRepository db) => _db = db;


        public IActionResult Index()
        {
            var prods = _db.GetList();
            return View(prods);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Assignment 3/Ass3Solution/eStore/Controllers/MemberController.cs
using BusinessObject.BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eStore.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMemberRepository _db;
        public MemberController(IMemberRepository db) => _db = db;

        public IActionResult Index()
        {
            var list = _db.GetList();
            return View(list);
        }

        public IActionResult Register() => View();

        [HttpPost]
        public IActionResult Register(string cPwd, Member member)
        {
            if (ModelState.IsValid)
            {
                var emailExist = _db.CheckEmail(member.Email);
                if (emailExist)
                {
                    ViewBag.error = "Email does exits";
                }
                else if (Equals(cPwd, member.Password))
                {
                    _db.InsertMember(member);
                    return Redirect("/");
                }
                else
                {
                    ViewBag.error = "Confirm Password invalid";
                }
            }
            return View();
        }

        public IActionResult Login() => View();

        [HttpPost]
        public IActionResult Login(string email, string pwd)
        {
            var member = _db.GetMemberByEmail(email);
            var check = _db.Login(email, pwd);
            if (check)
            {
                HttpContext.Session.SetString("user", email);
                HttpContext.Session.SetString("userID", Convert.ToString(member.MemberId));
                return Redirect("/");
            }
            ViewBag.error = "Login Failed";
            return View();
        }

        [HttpPost]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("user");
            HttpContext.Session.Remove("userID");
            return Redirect("/");
        }
    }
}

Assignment 3/Ass3Solution/eStore/Controllers/OrderController.cs
using BusinessObject.BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _db;
        public OrderController(IOrderRepository db) => _db = db;


        public IActionResult Index()
        {
            var list = _db.GetList();
            return View(list);
        }
        public IActionResult Create(string name, int price)
        {
            TempData["ProductName"] = name;
            TempData["Price"] = price;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                _db.InsertOrder(order);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult CancelOrder(int id)
        {
            _db.DeleteOrder(id);
            return RedirectToAction("Index");
        }
    }
}

Assignment 3/Ass3Solution/eStore/Controllers/ProductController.cs
using BusinessObject.BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _db;
        public ProductController(IProductRepository db) => _db = db;

        public IActionResult Index() => View();

        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                _db.InsertProduct(product);
                return Redirect("/");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            var product = _db.GetProduct(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                _db.DeleteProduct(id.Value);
            }
            return Redirect("/");
        }

        public IActionResult View(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.GetProduct(id.Value);
            return View(product);
        }

        public IActionResult Update(int id)
        {
            var product = _db.GetProduct(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Update(int? id, Product prod)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                _db.UpdateProduct(prod);
            }
            return Redirect("/");
        }
    }
}

Assignment 3/Ass3Solution/eStore/Controllers/SearchController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eStore.Controllers
{
    public class SearchController : Controller
    {
        public IActionResult Index() => View();
    }
}

Assignment 3/Ass3Solution/eStore/Views/Home/Index.cshtml
@model IEnumerable<BusinessObject.BusinessObject.Product>
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{
    ViewData["Title"] = "Home Page";

    var user = @HttpContextAccessor.HttpContext.Session.GetString("user");
}

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <aside>
                <div class="nav-shopping">
                    <h4>Shopping</h4>
                    <hr style="width:80%;text-align:left;margin-left:0;border-style:dotted;">
                    <ul>
                        <li style="list-style-type: none;">
                            <a asp-controller="Product">Products</a>
                        </li>
                        <hr style="width:75%;text-align:left;margin-left:0;border-style:dotted;">
                        <li style="list-style-type: none;">
                            <a asp-controller="Search">Search</a>
                        </li>
                        <hr style="width:75%;text-align:left;margin-left:0;border-style:dotted;">
                    </ul>
                </div>
                @if (user != null)
                {
                    <div class="nav-admin">
                        @if (user == "admin@fstore.com")
                        {
                            <h4>Administration</h4>
                            <hr style="width:80%;text-align:left;margin-left:0;border-style:dotted;">
                            <ul>
                                <li style="list-style-type: none;">
                                    <a asp-controller="Member">Members</a>
                                </li>
                                <hr style="width:75%;text-align:left;margin-left:0;border-style:dotted;">
                            </ul>
                        }
                        else
                        {
                            <h4>Customer</h4>
                            <hr style="width:80%;text-align:left;margin-left:0;border-style:dotted;">
                            <ul>
                                <li style="list-style-type: none;">
                                    <a asp-controller="Order">Orders</a>
                                </li>
                                <hr style="width:75%;text-align:left;margin-left:0;border-style:dotted;">
                            </ul>
                        }
                    </div>
                }
            </aside>
        </div>
        <div class="col-md-9">
            <table class="table table-bordered">
                <thead class="table-dark">
                <th>ID</th>
                <th>Product Name</th>
                <th>Weight</th>
                <th>Price</th>
                <th>Details</th>
                </thead>
                <tbody>
                    @{
                        int indexID = 1;
                    }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@indexID</td>
                            <td>@item.ProductName</td>
                            <td>@item.Weight Ibs</td>
                            <td>$@item.UnitPrice</td>
                            <td>
                                <a asp-controller="Product" asp-action="View" asp-route-Id="@item.ProductId" class="btn btn-outline-info">View</a>
                                @if (user != null)
                                {
                                    @if (user == "admin@fstore.com")
                                    {
                                        <a asp-controller="Product" asp-action="Update" class="btn btn-outline-success" asp-route-Id="@item.ProductId">Update</a>
                                        <a asp-controller="Product" asp-action="Delete" class="btn btn-outline-danger" asp-route-Id="@item.ProductId">Delete</a>
                                    }
                                    else
                                    {
                                        <a asp-controller="Order" asp-action="Create" class="btn btn-outline-warning" asp-route-name="@item.ProductName" asp-route-price="@item.UnitPrice">Order</a>
                                    }
                                }
                            </td>
                        </tr>
                        indexID++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>